name: 📚 Documentation Issue
description: Report missing, incorrect, or unclear documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Report issues or suggest improvements.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is affected?
      options:
        - README.md
        - Help Tab content
        - Code comments/JSDoc
        - CONTRIBUTING guide
        - Installation instructions
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear or confusing
        - Typo/grammatical error
        - Missing code examples
        - Broken links
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue? (file path, section, URL)
      placeholder: "e.g., README.md > Installation section"
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (if applicable)
      placeholder: "Quote the current text..."
    validations:
      required: false

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: "The documentation should..."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the documentation issue
      placeholder: "Add any other context..."
    validations:
      required: false
